eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 0

spring:
  application:
    name: notification-service

  # Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic #always send message to this topic by default
    consumer: # tell Spring Boot how to deserialize incoming key-value pairs
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: event:com.hieutt.notificationservice.event.OrderPlacedEvent #map the OrderPlacedEvent in order service to OrderPlacedEvent in noti service
      group-id: notificationId

management:
  # Distributed Tracing - Zipkin
  tracing:
    sampling:
      probability: 1.0 # send 100% of request to Zipkin
