server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411

spring:
  # Security Keycloak OAuth02
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/springboot-microservices-realm
