spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://mysql-order:3309/order-service
    password: root
  kafka:
    bootstrap-servers: broker:29092
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
