eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
server:
  port: '0'

# Distributed Tracing - Zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # send 100% of request to Zipkin


