spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://mysql-order:3307/inventory-service
    password: root
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka
