spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/inventory-service
    password: root
  application:
    name: inventory-service
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: '0'

# Distributed Tracing - Zipkin
management:
  tracing:
    sampling:
      probability: 1.0 # send 100% of request to Zipkin
